---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.namespace }}
  name: credentials
type: Opaque
stringData:
{{ tpl (.Files.Get "secrets/credentials.yaml") . | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.namespace }}
  name: seeds
type: Opaque
stringData:
{{ tpl (.Files.Get "secrets/seeds.yaml") . | indent 2 }}
