apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: InfluxDB
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true

- name: InfluxDB
  type: influxdb
  typeName: InfluxDB
  typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  password: ''
  user: ''
  database: telegraf
  basicAuth: false
  isDefault: false
  readOnly: false

- name: InfluxDB-Flux
  type: influxdb
  typeName: InfluxDB
  typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  password: ''
  user: ''
  database:
  basicAuth: false
  isDefault: false
  jsonData:
    defaultBucket: telegraf/autogen
    httpMode: POST
    organization: example-org
    version: Flux
  secureJsonData:
    token: ${INFLUX_DB_FLUX_TOKEN}
  readOnly: false
